services:
  vae_gan:
    image: "sagemaker-vae-gan:latest"
    build:
        context: ./vae_gan/
        dockerfile: Dockerfile
        platforms:
          - linux/amd64
    ports:
      -  "5004:5000"
  scaffold_constrained:
    image: "sagemaker-scaffold-constrained:latest"
    cpu_count: 2
    build:
      context: ./scaffold_constrained/
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "5005:5000"
  multi_objective:
    image: "sagemaker-multiobj-rationale:latest"
    build:
      context: ./multiobj-rationale
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "5006:5000"
  # web_server:
  #   image: "web_server:latest"
  #   build:
  #     context: ./web_server/
  #     dockerfile: Dockerfile
  #     platforms:
  #       - linux/amd64
  #   ports:
  #     - "5008:5000"