#!/bin/bash
# FILENAME: generate

#SBATCH -A cis220051-gpu
#SBATCH -p gpu		# Queue name
#SBATCH --nodes=1		# number of nodes
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --time=12:00:00		# wall time
#SBATCH --job-name MolGAN
#SBATCH -o myjob.o		# Name of stdout output file
#SBATCH -e myjob.e		# Name of stderr error file
#SBATCH --mail-user=shashank11297@gmail.com
#SBATCH --mail-type=all


module load anaconda
conda activate tensorflow
python train.py > output
echo "done"