services:
  vae_gan:
    image: "vae_gan:latest"
    build:
        context: ./vae_gan/
        dockerfile: Dockerfile
        platforms:
          - linux/amd64
    ports:
      -  "5004:5000"
  scaffold_constrained:
    image: "scaffold_constrained:latest"
    cpu_count: 2
    build:
      context: ./scaffold_constrained/
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "5005:5000"
  web_server:
    image: "web_server:latest"
    build:
      context: ./web_server/
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "5008:5000"